### ISSUE TITLE
Nicer parallel output

### ISSUE THREAD

**Issue by quarterto** [Financial-Times/athloi#1]
If running in a TTY show the output of all the tasks in separate Blessed (or whatever) panes

**Comment by i-like-robots** [comment]
The author of the monorepo management tool [oao](https://github.com/guigrpa/oao) also has a logger capable of handling parallel process output called [storyboard](https://github.com/guigrpa/storyboard).

Although the docs for this are not great it appears to be well written, is tested, and has a small dependency tree. I tried hacking it into Athloi and the output is definitely improved:

<img width="954" alt="screenshot 2019-02-13 at 09 22 52" src="https://user-images.githubusercontent.com/271645/52709563-01458580-2f85-11e9-854a-bc056c9e59cf.png">

Alternatively we could buffer the output this when the child process is closed. This is much simpler but may not be as desirable as it does not provide the immediate feedback. This technique is implemented by [wsrun](https://github.com/whoeverest/wsrun) which is quite similar to Athloi.
