### ISSUE TITLE
Dependency versions don't update when using version task with filter

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/athloi#14]
Running the version task with a filter will update the target package/s but not their dependencies. This is because there is an explicit list of dependencies to update. This also requires the addition of an option to specify a second version tag. This is as expected but allows packages to be published with invalid dependencies.

Steps to recreate:

```sh
npx athloi version v2.0.0 -F package-a
```

Output:

```json
{
  "name": "package-a",
  "version": "2.0.0",
  "dependencies": {
    "package-b": "file:../package-b"
  },
  "devDependencies": {
    "package-c": "file:../package-c"
  }
}
```

Expected:

```json
{
  "name": "package-a",
  "version": "2.0.0",
  "dependencies": {
    "package-b": "???"
  },
  "devDependencies": {
    "package-c": "???"
  }
}
```

**Comment by quarterto** [comment]
is this running in a full git checkout? can it use the latest `vx.y.z` git tag?

**Comment by i-like-robots** [comment]
There's no git info in Circle (I assume so nobody accidentally deploys it?) but we can checkout again if we need to. Otherwise 🙈 :

```sh
npm dist-tag ls package | grep 'latest: ' | sed 's/latest: //'
```

**Comment by i-like-robots** [comment]
After some discussion we have agreed that this tool does not have enough context to make these versioning decisions. The only change required therefore is to target only relative file paths (`file:..`) when bumping versions so that the tool does not overwrite any explicit resolutions.
