### ISSUE TITLE
readme does not explain "cross-dependencies" or "topological order"

### ISSUE THREAD

**Issue by apaleslimghost** [Financial-Times/athloi#70]
- these terms are quite jargony and confusing to a newcomer
- this also means the readme doesn't adequately explain how to set up your monorepo to work with athloi (i.e. using `file:` version specifiers in the `package.json`)

**Comment by i-like-robots** [comment]
Agreed. I don't remember where "cross-dependencies" came from but I'm not sure it's even Google-able 😬 I suspect "dependencies between packages within the monorepo" is better!

**Comment by wheresrhys** [comment]
Barely anybody uses this tool any more, and we probably should find a better solution. Not worth wasting time on better documentation
